### ISSUE TITLE
crane-scheduler-controller 健康检查失败，readness和liveness都失败

### ISSUE THREAD

**Issue by chinaboy007** [gocrane/crane-scheduler#41]
Events:
  Type     Reason     Age                   From               Message
  ----     ------     ----                  ----               -------
  Normal   Scheduled  5m27s                 default-scheduler  Successfully assigned crane-system/crane-scheduler-controller-5c85f47c45-trmzp to 192.168.227.164
  Normal   Pulled     5m37s                 kubelet            Container image "docker.io/gocrane/crane-scheduler-controller:0.0.23" already present on machine
  Normal   Created    5m37s                 kubelet            Created container crane-scheduler-controller
  Normal   Started    5m36s                 kubelet            Started container crane-scheduler-controller
  Warning  Unhealthy  32s (x31 over 5m32s)  kubelet            Readiness probe failed: Get "http://10.244.27.203:8090/healthz": dial tcp 10.244.27.203:8090: connect: connection refused

readness和liveness都失败，后面直接注释掉才正常启动。请修复此问题

**Comment by xieydd** [comment]
maybe initialDelaySeconds is too small , we will check this and fix the issue.

**Comment by chinaboy007** [comment]
> maybe initialDelaySeconds is too small , we will check this and fix the issue.

I have change initialDelaySeconds is 120s or 180s,but  Readiness probe  failed

**Comment by xieydd** [comment]
@chinaboy007 We found the problem, because this commit https://github.com/gocrane/crane-scheduler/commit/ccd57b806e1c7109b440e8873ca75db91337b461 was merged in after image version 0.0.23 https://github.com/gocrane/helm-charts/blob/main/charts/scheduler/values.yaml#L18 of the image, so the healthz healthz check will failure, you can update it to 0.0.24 image version. Thank you report the issue.

**Comment by chinaboy007** [comment]
经验证，已解决，谢谢！
